[supervisord]
nodaemon=true

[program:web]
command=gunicorn app:app --bind 0.0.0.0:8000
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout

[program:bot]
command=python3 main.py
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stdout_logfile=/dev/stdout
